local F = {}

local function solidify(str)
    local add = {}
    for name in string.gmatch(string.gsub(str, "%s+", ""), "%[fluid=([%a%d%-_:]+)%]") do
        add[#add + 1] = "[item=solid-" .. name .. "] "
    end
    return add == {} and (str) or (str .. " autogenerated solid fluids: " .. table.concat(add))
end

local presets = {
    ["DEFAULT"] = {
        localized_name = "vanilla",
        default_values = "(:[item=coal][item=stone][item=iron-ore][item=copper-ore]:1) ([item=electric-mining-drill][fluid=sulfuric-acid]:[item=uranium-ore]:3) (:[fluid=water]:0.0002) ([item=boiler]:[fluid=steam]:0.0002) ([item=pumpjack]:[fluid=crude-oil]:0.4)",
        not_random_recipes = "[recipe=nuclear-fuel-reprocessing]",
        not_random_resources = "[item=wood] [item=raw-fish]",
        not_random_categories = "",
        not_random_ingredients = "[item=rocket-part] [fluid=water] [fluid=steam]",
        not_random_ore_processing = true,
        forbidden_categories = "",
        forbidden_recipes = "",
        forbidden_ingredients = "[item=barrel]",
        forbidden_results = "[item=barrel]",
        prevent_duplicates = "smelting",
        starter_crafting = "crafting smelting",
    },
    ["IndustrialRevolution"] = {
        localized_name = "ir2",
        default_values = {"(:[item=wood][item=rubber-wood]:2) ([technology=ir2-gold-milestone]:[item=gold-ore]:1.5) (:[item=tin-ore]:1)"},
        not_random_recipes = "",
        not_random_resources = "[item=raw-fish] [item=ruby-gem] [item=sapphire-gem] [item=diamond-gem]",
        forbidden_categories = {"scrapping incinerating"},
        prevent_duplicates = {
            "smelting-2 smelting-3 grinding grinding-2 powdering powdering-2 powdering-3 charcoal-kiln forestry charging washing advanced-washing ingot-casting plate-casting gear-wheel-casting",
        },
    },
    ["Krastorio2"] = {
        localized_name = "krastorio-2",
        default_values = "(:[item=coal][item=stone][item=iron-ore][item=copper-ore]:1) ([item=electric-mining-drill][fluid=sulfuric-acid]:[item=uranium-ore]:3) (:[fluid=water]:0.005) ([item=boiler]:[fluid=steam]:0.005)  ([item=pumpjack]:[fluid=crude-oil]:0.4) ([item=kr-atmospheric-condenser]:[fluid=nitrogen][fluid=oxygen][fluid=hydrogen]:0.02) ([item=kr-mineral-water-pumpjack]:[fluid=mineral-water]:0.4) ([item=kr-quarry-drill]:[item=raw-imersite]:3) ([item=electric-mining-drill][fluid=chlorine]:[item=raw-rare-metals]:3) (:[item=wood]:0.05)",
        not_random_resources = "[item=raw-fish] [item=potato] [item=spoiled-potato]",
    },
    ["SeaBlockMetaPack"] = {
        localized_name = "sea-block",
        default_values = "(:[fluid=water]:0.0002) ([item=boiler]:[fluid=steam]:0.0002) (:[item=cellulose-fiber]:0.05) ([item=angels-air-filter]:[fluid=gas-compressed-air]:0.01) ([item=seafloor-pump]:[fluid=water-viscous-mud]:0.002)",
        not_random_recipes = "",
        not_random_resources = "[item=raw-fish] [item=temperate-garden] [item=desert-garden] [item=swamp-garden]",
        not_random_ingredients = "",
        not_random_ore_processing = false,
        starter_crafting = {"petrochem-electrolyser ore-sorting-t1 liquifying crystallizing bio-processing ore-refining-t1 angels-tree"},
    },
    ["omnimatter"] = {
        localized_name = "omnimatter",
        default_values = "(:[item=omnite]:0.1) (:[fluid=water]:0.0002) ([item=boiler]:[fluid=steam]:0.0002)",
        not_random_recipes = "",
        not_random_resources = "[item=wood] [item=raw-fish]",
        not_random_ore_processing = false,
        starter_crafting = {"omnite-extraction-burner"},
    },
    ["omnimatter_wood"] = {localized_name = "omnimatter-wood", default_values = {"(:[item=wood]:0)"}, not_random_resources = "[item=raw-fish]"},
    ["omnimatter_fluid"] = {localized_name = "omnimatter-fluid"},
    ["boblibrary"] = {localized_name = "bob-canisters", forbidden_ingredients = {"[item=empty-canister] [item=gas-canister]"}, forbidden_results = {"[item=empty-canister] [item=gas-canister]"}},
    ["FluidicPower"] = {localized_name = "fluidic-power", forbidden_categories = {"fluidic-generate fluidic-transformers"}},
	["space-age"] = {
		default_values = "(:[item=coal][item=stone][item=iron-ore][item=copper-ore]:1) ([item=electric-mining-drill][fluid=sulfuric-acid]:[item=uranium-ore]:3) (:[fluid=water]:0.0002) ([item=boiler]:[fluid=steam]:0.0002) ([item=pumpjack]:[fluid=crude-oil]:0.4) ([item=asteroid-collector]:[item=metallic-asteroid-chunk][item=carbonic-asteroid-chunk][item=oxide-asteroid-chunk]:10) ([item=thruster]:[item=yumako][item=jellynut]:3) ([item=thruster]:[item=spoilage]:1) ([item=thruster]:[item=pentapod-egg]:30) ([item=thruster]:[item=tungsten-ore]:6) ([item=thruster]:[item=calcite]:1) ([item=thruster]:[item=scrap]:1) ([item=recycler]:[item=holmium-ore]:5) ([item=capture-robot-rocket]:[item=biter-egg]:10) ([item=electromagnetic-science-pack][item=metallurgic-science-pack][item=agricultural-science-pack]:[fluid=lithium-brine][fluid=fluorine]:0.2) ([item=electromagnetic-science-pack][item=metallurgic-science-pack][item=agricultural-science-pack]:[fluid=ammoniacal-solution]:0.02) ([item=railgun-turret]:[item=promethium-asteroid-chunk]:20)",
		forbidden_ingredients = "[item=barrel][item=turbo-loader][item=express-loader][item=fast-loader][item=loader]",
        forbidden_results = "[item=barrel][item=turbo-loader][item=express-loader][item=fast-loader][item=loader]",
        not_random_ingredients = "[item=rocket-part] [fluid=water] [fluid=steam] [fluid=lava] [fluid=fusion-plasma]",
        not_random_recipes = "[recipe=nuclear-fuel-reprocessing] [recipe=fluoroketone-cooling]",
	}
}

function F.get()
    local loaded = {"DEFAULT"}
    for name, _ in pairs(presets) do
        if mods[name] then
            loaded[#loaded + 1] = name
        end
    end
    local preset = {localized_name = {"INFO"}}
    for _, p in pairs(loaded) do
        local pre = presets[p]
        preset.localized_name[#preset.localized_name + 1] = pre.localized_name
        for key, value in pairs(pre) do
            if key ~= "localized_name" then
                if type(value) == "table" then
                    preset[key][#preset[key] + 1] = value[1]
                else
                    preset[key] = {value}
                end
            end
        end
    end

    for key, value in pairs(preset) do
        if key ~= "localized_name" then
            if type(value) == "table" then
                if #value == 1 then
                    preset[key] = value[1]
                else
                    preset[key] = table.concat(value, " ")
                end
            end
        end
    end

    if mods["omnimatter_fluid"] then
        preset.not_random_resources = solidify(preset.not_random_resources)
        preset.not_random_ingredients = solidify(preset.not_random_ingredients)
        preset.forbidden_ingredients = solidify(preset.forbidden_ingredients)
        preset.forbidden_results = solidify(preset.forbidden_results)
    end

    return preset
end

return F
